// @ts-nocheck
// This file is autogenerated
// Do not edit this file directly.
import * as React from "react";

export const index: Record<
  string,
  {
    id: string;
    name: string;
    description: string;
    type: string;
    files: {
      path: string;
    }[];
    component?: React.LazyExoticComponent<() => React.JSX.Element>;
  }
> = {
  "ui/alert": {
    id: "ui/alert",
    name: "Alert",
    description: "",
    files: [{
      path: "ui/alert.tsx",
    }],
    
  },
  "ui/avatar": {
    id: "ui/avatar",
    name: "Avatar",
    description: "",
    files: [{
      path: "ui/avatar.tsx",
    }],
    
  },
  "ui/badge": {
    id: "ui/badge",
    name: "Badge",
    description: "",
    files: [{
      path: "ui/badge.tsx",
    }],
    
  },
  "ui/button": {
    id: "ui/button",
    name: "Button",
    description: "",
    files: [{
      path: "ui/button.tsx",
    }],
    
  },
  "ui/card": {
    id: "ui/card",
    name: "Card",
    description: "",
    files: [{
      path: "ui/card.tsx",
    }],
    
  },
  "ui/checkbox": {
    id: "ui/checkbox",
    name: "Checkbox",
    description: "",
    files: [{
      path: "ui/checkbox.tsx",
    }],
    
  },
  "ui/dialog": {
    id: "ui/dialog",
    name: "Dialog",
    description: "",
    files: [{
      path: "ui/dialog.tsx",
    }],
    
  },
  "ui/dropdown-menu": {
    id: "ui/dropdown-menu",
    name: "Dropdown Menu",
    description: "",
    files: [{
      path: "ui/dropdown-menu.tsx",
    }],
    
  },
  "ui/field": {
    id: "ui/field",
    name: "Field",
    description: "",
    files: [{
      path: "ui/field.tsx",
    }],
    
  },
  "ui/hover-card": {
    id: "ui/hover-card",
    name: "Hover Card",
    description: "",
    files: [{
      path: "ui/hover-card.tsx",
    }],
    
  },
  "ui/icon-button": {
    id: "ui/icon-button",
    name: "Icon-button",
    description: "",
    files: [{
      path: "ui/icon-button.tsx",
    }],
    
  },
  "ui/input": {
    id: "ui/input",
    name: "Input",
    description: "",
    files: [{
      path: "ui/input.tsx",
    }],
    
  },
  "ui/popover": {
    id: "ui/popover",
    name: "Popover",
    description: "",
    files: [{
      path: "ui/popover.tsx",
    }],
    
  },
  "ui/progress": {
    id: "ui/progress",
    name: "Progress",
    description: "",
    files: [{
      path: "ui/progress.tsx",
    }],
    
  },
  "ui/prompt": {
    id: "ui/prompt",
    name: "Prompt",
    description: "",
    files: [{
      path: "ui/prompt.tsx",
    }],
    
  },
  "ui/radio": {
    id: "ui/radio",
    name: "Radio",
    description: "",
    files: [{
      path: "ui/radio.tsx",
    }],
    
  },
  "ui/select": {
    id: "ui/select",
    name: "Select",
    description: "",
    files: [{
      path: "ui/select.tsx",
    }],
    
  },
  "ui/separator": {
    id: "ui/separator",
    name: "Separator",
    description: "",
    files: [{
      path: "ui/separator.tsx",
    }],
    
  },
  "ui/sheet": {
    id: "ui/sheet",
    name: "Sheet",
    description: "",
    files: [{
      path: "ui/sheet.tsx",
    }],
    
  },
  "ui/slider": {
    id: "ui/slider",
    name: "Slider",
    description: "",
    files: [{
      path: "ui/slider.tsx",
    }],
    
  },
  "ui/stack": {
    id: "ui/stack",
    name: "Stack",
    description: "",
    files: [{
      path: "ui/stack.tsx",
    }],
    
  },
  "ui/switch": {
    id: "ui/switch",
    name: "Switch",
    description: "",
    files: [{
      path: "ui/switch.tsx",
    }],
    
  },
  "ui/tabs": {
    id: "ui/tabs",
    name: "Tabs",
    description: "",
    files: [{
      path: "ui/tabs.tsx",
    }],
    
  },
  "ui/table": {
    id: "ui/table",
    name: "Table",
    description: "",
    files: [{
      path: "ui/table.tsx",
    }],
    
  },
  "ui/text": {
    id: "ui/text",
    name: "Text",
    description: "",
    files: [{
      path: "ui/text.tsx",
    }],
    
  },
  "ui/textarea": {
    id: "ui/textarea",
    name: "Textarea",
    description: "",
    files: [{
      path: "ui/textarea.tsx",
    }],
    
  },
  "ui/tooltip": {
    id: "ui/tooltip",
    name: "Tooltip",
    description: "",
    files: [{
      path: "ui/tooltip.tsx",
    }],
    
  },
  "examples/alert-01": {
    id: "examples/alert-01",
    name: "Alert 01",
    description: "",
    files: [{
      path: "examples/alert-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/alert-01.tsx"))
  },
  "examples/alert-02": {
    id: "examples/alert-02",
    name: "Alert 02",
    description: "",
    files: [{
      path: "examples/alert-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/alert-02.tsx"))
  },
  "examples/avatar-01": {
    id: "examples/avatar-01",
    name: "Avatar 01",
    description: "",
    files: [{
      path: "examples/avatar-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/avatar-01.tsx"))
  },
  "examples/badge-01": {
    id: "examples/badge-01",
    name: "Badge 01",
    description: "",
    files: [{
      path: "examples/badge-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/badge-01.tsx"))
  },
  "examples/badge-02": {
    id: "examples/badge-02",
    name: "Badge 02",
    description: "",
    files: [{
      path: "examples/badge-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/badge-02.tsx"))
  },
  "examples/button-01": {
    id: "examples/button-01",
    name: "Button 01",
    description: "",
    files: [{
      path: "examples/button-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/button-01.tsx"))
  },
  "examples/button-02": {
    id: "examples/button-02",
    name: "Button 02",
    description: "",
    files: [{
      path: "examples/button-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/button-02.tsx"))
  },
  "examples/button-03": {
    id: "examples/button-03",
    name: "Button 03",
    description: "",
    files: [{
      path: "examples/button-03.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/button-03.tsx"))
  },
  "examples/card-01": {
    id: "examples/card-01",
    name: "Card 01",
    description: "",
    files: [{
      path: "examples/card-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/card-01.tsx"))
  },
  "examples/checkbox-01": {
    id: "examples/checkbox-01",
    name: "Checkbox 01",
    description: "",
    files: [{
      path: "examples/checkbox-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/checkbox-01.tsx"))
  },
  "examples/checkbox-02": {
    id: "examples/checkbox-02",
    name: "Checkbox 02",
    description: "",
    files: [{
      path: "examples/checkbox-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/checkbox-02.tsx"))
  },
  "examples/dialog-01": {
    id: "examples/dialog-01",
    name: "Dialog 01",
    description: "",
    files: [{
      path: "examples/dialog-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/dialog-01.tsx"))
  },
  "examples/dropdown-menu-01": {
    id: "examples/dropdown-menu-01",
    name: "Menu 01",
    description: "",
    files: [{
      path: "examples/dropdown-menu-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/dropdown-menu-01.tsx"))
  },
  "examples/field-01": {
    id: "examples/field-01",
    name: "Field 01",
    description: "",
    files: [{
      path: "examples/field-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/field-01.tsx"))
  },
  "examples/field-02": {
    id: "examples/field-02",
    name: "Field 02",
    description: "",
    files: [{
      path: "examples/field-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/field-02.tsx"))
  },
  "examples/hover-card-01": {
    id: "examples/hover-card-01",
    name: "Hover Card 01",
    description: "",
    files: [{
      path: "examples/hover-card-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/hover-card-01.tsx"))
  },
  "examples/icon-button-01": {
    id: "examples/icon-button-01",
    name: "Icon Button 01",
    description: "",
    files: [{
      path: "examples/icon-button-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/icon-button-01.tsx"))
  },
  "examples/icon-button-02": {
    id: "examples/icon-button-02",
    name: "Icon Button 02",
    description: "",
    files: [{
      path: "examples/icon-button-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/icon-button-02.tsx"))
  },
  "examples/input-01": {
    id: "examples/input-01",
    name: "Input 01",
    description: "",
    files: [{
      path: "examples/input-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/input-01.tsx"))
  },
  "examples/popover-01": {
    id: "examples/popover-01",
    name: "Popover 01",
    description: "",
    files: [{
      path: "examples/popover-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/popover-01.tsx"))
  },
  "examples/progress-01": {
    id: "examples/progress-01",
    name: "Progress 01",
    description: "",
    files: [{
      path: "examples/progress-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/progress-01.tsx"))
  },
  "examples/prompt-01": {
    id: "examples/prompt-01",
    name: "Prompt 01",
    description: "",
    files: [{
      path: "examples/prompt-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/prompt-01.tsx"))
  },
  "examples/radio-01": {
    id: "examples/radio-01",
    name: "Radio 01",
    description: "",
    files: [{
      path: "examples/radio-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/radio-01.tsx"))
  },
  "examples/radio-02": {
    id: "examples/radio-02",
    name: "Radio 02",
    description: "",
    files: [{
      path: "examples/radio-02.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/radio-02.tsx"))
  },
  "examples/sheet-01": {
    id: "examples/sheet-01",
    name: "Sheet 01",
    description: "",
    files: [{
      path: "examples/sheet-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/sheet-01.tsx"))
  },
  "examples/select-01": {
    id: "examples/select-01",
    name: "Select 01",
    description: "",
    files: [{
      path: "examples/select-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/select-01.tsx"))
  },
  "examples/separator-01": {
    id: "examples/separator-01",
    name: "Separator 01",
    description: "",
    files: [{
      path: "examples/separator-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/separator-01.tsx"))
  },
  "examples/slider-01": {
    id: "examples/slider-01",
    name: "Slider 01",
    description: "",
    files: [{
      path: "examples/slider-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/slider-01.tsx"))
  },
  "examples/switch-01": {
    id: "examples/switch-01",
    name: "Switch 01",
    description: "",
    files: [{
      path: "examples/switch-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/switch-01.tsx"))
  },
  "examples/table-01": {
    id: "examples/table-01",
    name: "Table 01",
    description: "",
    files: [{
      path: "examples/table-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/table-01.tsx"))
  },
  "examples/tabs-01": {
    id: "examples/tabs-01",
    name: "Tabs 01",
    description: "",
    files: [{
      path: "examples/tabs-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/tabs-01.tsx"))
  },
  "examples/text-01": {
    id: "examples/text-01",
    name: "Text 01",
    description: "",
    files: [{
      path: "examples/text-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/text-01.tsx"))
  },
  "examples/textarea-01": {
    id: "examples/textarea-01",
    name: "Textarea 01",
    description: "",
    files: [{
      path: "examples/textarea-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/textarea-01.tsx"))
  },
  "examples/tooltip-01": {
    id: "examples/tooltip-01",
    name: "Tooltip 01",
    description: "",
    files: [{
      path: "examples/tooltip-01.tsx",
    }],
    component: React.lazy(() => import("@/src/components/examples/tooltip-01.tsx"))
  },
};
